### ISSUE TITLE
How to Upload Feedback Using the API？

### ISSUE THREAD

**Issue by CreepyJ** [clearflask/clearflask#138]
I want use the api `/project/{projectID}/idea` api to Upload Feedback, and I keep getting `403 Forbidden` response code.
It seems that I have to log in to send Feedback.
I want to add user feedback functionality to a desktop application, Is there any why to achieve this?

**Comment by matusfaro** [comment]
You need to register a user account. But you can setup your project to allow anonymous accounts that don't require an email or even a name.

Register an account first using:
POST /project/{projectId}/user

If successful, you will be assigned a cookie.

With the same session (with the cookie), you can then post new feedback.

You can test out and view all API endpoints here: https://clearflask.com/api/

**Comment by CreepyJ** [comment]
@matusfaro I have set to allow anonymous accounts. 
So I don't have to add any parameters?
I call this api `POST /project/{projectId}/user` and get exception:
```
clearflask-server-1   | Caused by: java.lang.NullPointerException: null
clearflask-server-1   |         at com.smotana.clearflask.web.resource.UserResource.userCreate(UserResource.java:165)
clearflask-server-1   |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
clearflask-server-1   |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
clearflask-server-1   |         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
clearflask-server-1   |         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
clearflask-server-1   |         at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
clearflask-server-1   |         at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
clearflask-server-1   |         at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
clearflask-server-1   |         at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:243)
clearflask-server-1   |         at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
clearflask-server-1   |         at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
clearflask-server-1   |         at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
clearflask-server-1   |         at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
clearflask-server-1   |         at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
clearflask-server-1   |         at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
clearflask-server-1   |         at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
clearflask-server-1   |         at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
clearflask-server-1   |         at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
clearflask-server-1   |         at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
clearflask-server-1   |         at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
clearflask-server-1   |         at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
clearflask-server-1   |         at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
clearflask-server-1   |         at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
clearflask-server-1   |         ... 36 common frames omitted
clearflask-server-1   | 22-Feb-2024 07:18:58.253 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [api] in context with path [] threw exception [java.lang.NullPointerException] with root cause
clearflask-server-1   |         java.lang.NullPointerException
clearflask-server-1   |                 at com.smotana.clearflask.web.resource.UserResource.userCreate(UserResource.java:165)
clearflask-server-1   |                 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
clearflask-server-1   |                 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
clearflask-server-1   |                 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
clearflask-server-1   |                 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
clearflask-server-1   |                 at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
clearflask-server-1   |                 at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
clearflask-server-1   |                 at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
clearflask-server-1   |                 at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:243)
clearflask-server-1   |                 at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
clearflask-server-1   |                 at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
clearflask-server-1   |                 at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
clearflask-server-1   |                 at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
clearflask-server-1   |                 at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
clearflask-server-1   |                 at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
clearflask-server-1   |                 at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
clearflask-server-1   |                 at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
clearflask-server-1   |                 at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
clearflask-server-1   |                 at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
clearflask-server-1   |                 at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
clearflask-server-1   |                 at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
clearflask-server-1   |                 at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
clearflask-server-1   |                 at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
clearflask-server-1   |                 at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
clearflask-server-1   |                 at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
clearflask-server-1   |                 at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
clearflask-server-1   |                 at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
clearflask-server-1   |                 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
clearflask-server-1   |                 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
clearflask-server-1   |                 at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
clearflask-server-1   |                 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
clearflask-server-1   |                 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
clearflask-server-1   |                 at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
clearflask-server-1   |                 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
clearflask-server-1   |                 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
clearflask-server-1   |                 at com.smotana.clearflask.web.filter.HttpRedirectorFilter.doFilter(HttpRedirectorFilter.java:57)
clearflask-server-1   |                 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
clearflask-server-1   |                 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
clearflask-server-1   |                 at com.smotana.clearflask.web.filter.ApiExceptionMapperFilter.doFilter(ApiExceptionMapperFilter.java:49)
clearflask-server-1   |                 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
clearflask-server-1   |                 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
clearflask-server-1   |                 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
clearflask-server-1   |                 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
clearflask-server-1   |                 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
clearflask-server-1   |                 at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:571)
clearflask-server-1   |                 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
clearflask-server-1   |                 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
clearflask-server-1   |                 at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:698)
clearflask-server-1   |                 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
clearflask-server-1   |                 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:367)
clearflask-server-1   |                 at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:639)
clearflask-server-1   |                 at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
clearflask-server-1   |                 at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:882)
clearflask-server-1   |                 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1693)
clearflask-server-1   |                 at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
clearflask-server-1   |                 at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
clearflask-server-1   |                 at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
clearflask-server-1   |                 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
clearflask-server-1   |                 at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by matusfaro** [comment]
It's not intuitive, but you still have to pass in a body with `{}`.

I would suggest that you go into your portal, register a user and post a new message while inspecting the browser's Network tab to see exactly what API calls are made.

**Comment by CreepyJ** [comment]
It works fine now, thanks for helping
