### ISSUE TITLE
Email Delivery Failure 

### ISSUE THREAD

**Issue by ZandercraftGames** [clearflask/clearflask#60]
I have tried all of the various SMTP options for mail delivery, however, the server fails to properly send mail regardless of the method I use. It recognizes the method it is attempting to send with, but always fails with an error stating that there is no appropriate protocol.

```
org.simplejavamail.mailer.internal.MailerException: Third party error
	at org.simplejavamail.mailer.internal.SendMailClosure.executeClosure(SendMailClosure.java:91)
	at org.simplejavamail.mailer.internal.AbstractProxyServerSyncingClosure.run(AbstractProxyServerSyncingClosure.java:56)
	at org.simplejavamail.internal.util.concurrent.AsyncOperationHelper$1.run(AsyncOperationHelper.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.mail.MessagingException: Could not convert socket to TLS
	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:1907)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:666)
	at javax.mail.Service.connect(Service.java:317)
	at javax.mail.Service.connect(Service.java:176)
	at javax.mail.Service.connect(Service.java:125)
	at org.simplejavamail.mailer.internal.util.TransportRunner.runOnSessionTransport(TransportRunner.java:75)
	at org.simplejavamail.mailer.internal.util.TransportRunner.sendMessage(TransportRunner.java:48)
	at org.simplejavamail.mailer.internal.SendMailClosure.executeClosure(SendMailClosure.java:82)
	... 7 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:170)
	at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:98)
	at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:221)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:443)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:549)
	at com.sun.mail.util.SocketFetcher.startTLS(SocketFetcher.java:486)
	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:1902)
	... 14 common frames omitted
05:17:06.349 [pool-24-thread-1] WARN  c.s.c.c.p.provider.EmailServiceImpl - Email cannot be delivered
```

It, however, properly reflects the options as I change them in the config.
```
DEBUG o.s.m.internal.util.SessionLogger - starting async mail with session (host: smtp.<REDACTED>.com, port: 587, username: <REDACTED>, authenticate: true, transport: SMTP)
```
```
DEBUG o.s.m.internal.util.SessionLogger - starting async mail with session (host: smtp.<REDACTED>.com, port: 587, username: <REDACTED>, authenticate: true, transport: SMTPS)
```
```
DEBUG o.s.m.internal.util.SessionLogger - starting async mail with session (host: smtp.<REDACTED>.com, port: 587, username: <REDACTED>, authenticate: true, transport: SMTP_TLS)
```

**Comment by matusfaro** [comment]
Which TLS/SSL protocols does your SMTP allow? You can use `nmap` for this:
```
nmap --script ssl-enum-ciphers -p 443 smtp.<YOUR_SERVER>.com
```

Java11 only supports TLSv1.2+ so most likely your SMTP server only uses an older version.

**Comment by ZandercraftGames** [comment]
> Which TLS/SSL protocols does your SMTP allow? You can use `nmap` for this:
> 
> ```
> nmap --script ssl-enum-ciphers -p 443 smtp.<YOUR_SERVER>.com
> ```
> 
> Java11 only supports TLSv1.2+ so most likely your SMTP server only uses an older version.

Seems it supports TLSv1.2:
```
PORT    STATE SERVICE
587/tcp open  submission
| ssl-enum-ciphers: 
|   TLSv1.0: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (ecdh_x25519) - A
|       TLS_DHE_RSA_WITH_AES_256_CBC_SHA (dh 2048) - A
|       TLS_DHE_RSA_WITH_AES_128_CBC_SHA (dh 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors: 
|       NULL
|     cipher preference: server
|     warnings: 
|       64-bit block cipher 3DES vulnerable to SWEET32 attack
|   TLSv1.1: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (ecdh_x25519) - A
|       TLS_DHE_RSA_WITH_AES_256_CBC_SHA (dh 2048) - A
|       TLS_DHE_RSA_WITH_AES_128_CBC_SHA (dh 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors: 
|       NULL
|     cipher preference: server
|     warnings: 
|       64-bit block cipher 3DES vulnerable to SWEET32 attack
|   TLSv1.2: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (ecdh_x25519) - A
|       TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (dh 2048) - A
|       TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (dh 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (ecdh_x25519) - A
|       TLS_DHE_RSA_WITH_AES_256_CBC_SHA (dh 2048) - A
|       TLS_DHE_RSA_WITH_AES_128_CBC_SHA (dh 2048) - A
|       TLS_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors: 
|       NULL
|     cipher preference: server
```

**Comment by matusfaro** [comment]
Hmm, the docker container has this under `$JAVA_HOME/conf/security/java.security`:
```
jdk.tls.disabledAlgorithms=SSLv3, TLSv1, TLSv1.1, RC4, DES, MD5withRSA, \
    DH keySize < 1024, EC keySize < 224, 3DES_EDE_CBC, anon, NULL, \
    include jdk.disabled.namedCurves
```
So it seems to be fine unless I'm misreading it.

Can you modify your `docker-compose.yml` file to include the following JAVA_OPTS:
```
  clearflask-server:
    ...
    environment:
      - ...
      - JAVA_OPTS="-Djavax.net.debug=ssl"
```
Then restart and look at the extra logs. You should see logs similar to the following:
```
Ignoring unavailable cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
...
```
Please post the output including anything interesting around it.

The alternate option you have is to modify the docker container to comment out the `jdk.tls.disabledAlgorithms` in `$JAVA_HOME/conf/security/java.security` line and try it out. If it works, just keep using that modified container.

**Comment by ZandercraftGames** [comment]
This is what I've got so far from it:
```
05-May-2022 06:01:38.106 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djavax.net.debug=ssl
javax.net.ssl|DEBUG|12|localhost-startStop-1|2022-05-05 06:01:50.599 UTC|SSLCipher.java:438|jdk.tls.keyLimits:  entry = AES/GCM/NoPadding KeyUpdate 2^37. AES/GCM/NOPADDING:KEYUPDATE = 137438953472
```

**Comment by matusfaro** [comment]
Oh you should try to send an email with this extra logging and see what gets printed

**Comment by ZandercraftGames** [comment]
So a few things. There should be an option to let us specify the sending domain. The issue may have something to do with the fact that it's trying to send from @help.zandercraft.ca and not @zandercraft.ca. There should also be an option to change the email sending name to allow for more clearly specifying where the email is coming from. Most people won't understand what ClearFlask is who use the site, so it would be helpful to be able to set it to something like "Help Centre".  Would also be helpful if 

More related to the issue itself, here's a full log of it sending an email: https://pastebin.com/gyWbp1PP

**Comment by matusfaro** [comment]
Try the different options for `smtpStrategy` config, options are SMTP, SMTP_TLS, SMTPS. This may be misconfigured.
```
com.smotana.clearflask.core.push.provider.EmailServiceImpl$Config.smtpStrategy=<SMTP, SMTP_TLS, SMTPS>
```

---

I am adding a config property for overriding the domain name, in a few hours check for version `1.5.9`. Also you will be able to modify the local part as well (ie `noreply@...`).
```
com.smotana.clearflask.core.push.provider.EmailServiceImpl$Config.fromEmailLocalPart=noreply
com.smotana.clearflask.core.push.provider.EmailServiceImpl$Config.fromEmailDomainOverride=zandercraft.ca
```

---

There already is a config for overriding email sending name:
```
com.smotana.clearflask.core.push.provider.EmailServiceImpl$Config.emailDisplayName=ZanderCraft
```
All available configs for `1.5.8` are listed here:
https://github.com/clearflask/clearflask/blob/1.5.8/clearflask-server/src/main/java/com/smotana/clearflask/core/push/provider/EmailServiceImpl.java

**Comment by matusfaro** [comment]
Assuming this is resolved

**Comment by ZandercraftGames** [comment]
Apologies. I've been busy for the past few days. The issue still persists.

**Comment by matusfaro** [comment]
No problem, whenever you have time you can post an update to my suggestions and re-open this issue and I'll help you out.
