### ISSUE TITLE
API Endpoints respond with 463

### ISSUE THREAD

**Issue by neldridge** [clearflask/clearflask#82]
Hi,

I've set up a self-hosted CF on AWS following the instructions from the README. 

Resources used:
* ALB
* EC2 Instance
* OpenSearch
* S3
* DynamoDB table is being created as expected by CF

server/config-selfhost.cfg
```
com.smotana.clearflask.security.limiter.challenge.CaptchaChallenger$Config.enabled=false
com.smotana.clearflask.store.dynamo.DefaultDynamoDbProvider$Config.productionRegion=us-east-1
com.smotana.clearflask.store.elastic.DefaultElasticSearchProvider$Config.serviceEndpoint=https://redacted.us-east-1.es.amazonaws.com
com.smotana.clearflask.core.push.provider.BrowserPushServiceImpl$Config.publicKey=redacted
com.smotana.clearflask.core.push.provider.BrowserPushServiceImpl$Config.privateKey=redacted
com.smotana.clearflask.util.DefaultServerSecret$Config.sharedKey:cursor=redacted
com.smotana.clearflask.store.impl.DynamoElasticUserStore$Config.tokenSignerPrivKey=redacted
com.smotana.clearflask.web.Application$Config.domain=ideas.sub.domain.com
com.smotana.clearflask.web.security.AuthCookieImpl$Config.authCookieSecure=true
com.smotana.clearflask.web.Application$Config.startupWaitUntilDeps=true
com.smotana.clearflask.security.ClearFlaskSso$Config.secretKey=redacted
com.smotana.clearflask.web.security.SuperAdminPredicate$Config.superAdminEmailRegex=^email@domain.com$
com.smotana.clearflask.web.resource.AccountResource$Config.signupEnabled=true
com.smotana.clearflask.store.impl.DynamoElasticAccountStore$Config.createIndexOnStartup=true
com.smotana.clearflask.web.security.AuthenticationFilter$Config.connectToken=redacted
com.smotana.clearflask.core.push.provider.EmailServiceImpl$Config.useService=smtp
com.smotana.clearflask.core.push.provider.EmailServiceImpl$Config.smtpStrategy=SMTP_TLS
com.smotana.clearflask.core.push.provider.EmailServiceImpl$Config.smtpHost=smtp.office365.com
com.smotana.clearflask.core.push.provider.EmailServiceImpl$Config.smtpPort=587
com.smotana.clearflask.core.push.provider.EmailServiceImpl$Config.smtpUser=redacted
com.smotana.clearflask.core.push.provider.EmailServiceImpl$Config.smtpPassword=redacted
com.smotana.clearflask.core.push.provider.EmailServiceImpl$Config.emailDisplayName=redacted
com.smotana.clearflask.core.push.provider.EmailServiceImpl$Config.fromEmailLocalPart=redacted
com.smotana.clearflask.core.push.provider.EmailServiceImpl$Config.fromEmailDomainOverride=domain.com
com.smotana.clearflask.store.s3.DefaultS3ClientProvider$Config.dnsResolverTo=localstack
com.smotana.clearflask.store.s3.DefaultS3ClientProvider$Config.productionRegion=us-east-1
com.smotana.clearflask.store.impl.S3ContentStore$Config.bucketName=redacted
com.smotana.clearflask.store.impl.S3ContentStore$Config.scheme=https
com.smotana.clearflask.store.impl.S3ContentStore$Config.createBucket=false
com.smotana.clearflask.store.github.GitHubStoreImpl$Config.enabled=false


```

connect/connect.config.json
```
{
    "connectToken": "redacted",
    "disableAutoFetchCertificate": true,
    "forceRedirectHttpToHttps": true,
    "parentDomain": "ideas.sub.domain.com",
    "apiBasePath": "https://ideas.sub.domain.com"
}
```

Startup logs (minus DEBUG/TRACE and redacted some information)
https://gist.github.com/neldridge/fb058df63738f43d5266a5ce0c14e513 
There's nothing really helpful in this or in the DEBUG/TRACE. Maybe there's something I can turn on to enable better logging in the frontend?

console log
```
react-i18next:: It seems you are still using the old wait option, you may migrate to the new useSuspense behaviour.
(anonymous) @ createClass.js:124
n @ toPrimitive.js:11
o @ toPrimitive.js:22
h @ TouchRipple.js:36
A @ LanguageSelect.tsx:116
Jo @ react-lifecycles-compat.es.js:153
xs @ react-lifecycles-compat.es.js:261
gu @ react-lifecycles-compat.es.js:246
mu @ react-lifecycles-compat.es.js:246
su @ react-lifecycles-compat.es.js:239
ru @ react-lifecycles-compat.es.js:230
Wu @ react-lifecycles-compat.es.js:281
(anonymous) @ react-lifecycles-compat.es.js:284
cu @ react-lifecycles-compat.es.js:240
Zu @ react-lifecycles-compat.es.js:284
t.hydrate @ react-lifecycles-compat.es.js:290
(anonymous) @ index-csr.tsx:21
Promise.then (async)
j @ verify-stream.js:551
827 @ index-csr.tsx:20
r @ bootstrap:89
807 @ index.ts:16
r @ bootstrap:89
s @ bootstrap:45
n @ bootstrap:32
(anonymous) @ 85.4b71ce8d.chunk.js:2
cache.ts:31 Uncaught (in promise) TypeError: a is not a constructor
    at e.value (cache.ts:31:24)
    at Object.apply (server.ts:222:37)
    at AccountEnterPage.tsx:273:10
value @ cache.ts:31
apply @ server.ts:222
(anonymous) @ AccountEnterPage.tsx:273
Promise.then (async)
value @ AccountEnterPage.tsx:272
Ua @ react-lifecycles-compat.es.js:182
qa @ react-lifecycles-compat.es.js:181
xs @ react-lifecycles-compat.es.js:263
gu @ react-lifecycles-compat.es.js:246
mu @ react-lifecycles-compat.es.js:246
su @ react-lifecycles-compat.es.js:239
ru @ react-lifecycles-compat.es.js:230
Wu @ react-lifecycles-compat.es.js:281
(anonymous) @ react-lifecycles-compat.es.js:284
cu @ react-lifecycles-compat.es.js:240
Zu @ react-lifecycles-compat.es.js:284
t.hydrate @ react-lifecycles-compat.es.js:290
(anonymous) @ index-csr.tsx:21
Promise.then (async)
j @ verify-stream.js:551
827 @ index-csr.tsx:20
r @ bootstrap:89
807 @ index.ts:16
r @ bootstrap:89
s @ bootstrap:45
n @ bootstrap:32
(anonymous) @ 85.4b71ce8d.chunk.js:2
createClass.js:153          GET https://ideas.sub.domain.com/api/v1/admin/plan 463
(anonymous) @ createClass.js:153
(anonymous) @ runtime.ts:83
l @ createForOfIteratorHelper.js:63
(anonymous) @ createForOfIteratorHelper.js:293
(anonymous) @ createForOfIteratorHelper.js:118
n @ browser.ts:3
s @ browser.ts:25
(anonymous) @ browser.ts:32
(anonymous) @ browser.ts:21
(anonymous) @ runtime.ts:25
(anonymous) @ runtime.ts:47
l @ createForOfIteratorHelper.js:63
(anonymous) @ createForOfIteratorHelper.js:293
(anonymous) @ createForOfIteratorHelper.js:118
n @ browser.ts:3
s @ browser.ts:25
(anonymous) @ browser.ts:32
(anonymous) @ browser.ts:21
(anonymous) @ runtime.ts:21
(anonymous) @ PlanAdminApi.ts:46
l @ createForOfIteratorHelper.js:63
(anonymous) @ createForOfIteratorHelper.js:293
(anonymous) @ createForOfIteratorHelper.js:118
n @ browser.ts:3
s @ browser.ts:25
(anonymous) @ browser.ts:32
(anonymous) @ browser.ts:21
(anonymous) @ PlanAdminApi.ts:37
(anonymous) @ PlanAdminApi.ts:59
l @ createForOfIteratorHelper.js:63
(anonymous) @ createForOfIteratorHelper.js:293
(anonymous) @ createForOfIteratorHelper.js:118
n @ browser.ts:3
s @ browser.ts:25
(anonymous) @ browser.ts:32
(anonymous) @ browser.ts:21
(anonymous) @ PlanAdminApi.ts:37
value @ index.ts:2615
apply @ server.ts:221
(anonymous) @ AccountEnterPage.tsx:273
Promise.then (async)
value @ AccountEnterPage.tsx:272
Ua @ react-lifecycles-compat.es.js:182
qa @ react-lifecycles-compat.es.js:181
xs @ react-lifecycles-compat.es.js:263
gu @ react-lifecycles-compat.es.js:246
mu @ react-lifecycles-compat.es.js:246
su @ react-lifecycles-compat.es.js:239
ru @ react-lifecycles-compat.es.js:230
Wu @ react-lifecycles-compat.es.js:281
(anonymous) @ react-lifecycles-compat.es.js:284
cu @ react-lifecycles-compat.es.js:240
Zu @ react-lifecycles-compat.es.js:284
t.hydrate @ react-lifecycles-compat.es.js:290
(anonymous) @ index-csr.tsx:21
Promise.then (async)
j @ verify-stream.js:551
827 @ index-csr.tsx:20
r @ bootstrap:89
807 @ index.ts:16
r @ bootstrap:89
s @ bootstrap:45
n @ bootstrap:32
(anonymous) @ 85.4b71ce8d.chunk.js:2
Show 10 more frames
createClass.js:124 Server error: 463 failed plansGet
browser.ts:6 Uncaught (in promise) Response {__sentry_captured__: true, type: 'basic', url: 'https://ideas.sub.domain.com/api/v1/admin/plan', redirected: false, status: 463, …}
n @ browser.ts:6
u @ browser.ts:29
Promise.then (async)
n @ browser.ts:13
u @ browser.ts:29
Promise.then (async)
n @ browser.ts:13
s @ browser.ts:25
(anonymous) @ browser.ts:32
(anonymous) @ browser.ts:21
(anonymous) @ server.ts:43
(anonymous) @ serverAdmin.ts:54
apply @ server.ts:209
value @ index.ts:2607
apply @ server.ts:221
(anonymous) @ AccountEnterPage.tsx:273
Promise.then (async)
value @ AccountEnterPage.tsx:272
Ua @ react-lifecycles-compat.es.js:182
qa @ react-lifecycles-compat.es.js:181
xs @ react-lifecycles-compat.es.js:263
gu @ react-lifecycles-compat.es.js:246
mu @ react-lifecycles-compat.es.js:246
su @ react-lifecycles-compat.es.js:239
ru @ react-lifecycles-compat.es.js:230
Wu @ react-lifecycles-compat.es.js:281
(anonymous) @ react-lifecycles-compat.es.js:284
cu @ react-lifecycles-compat.es.js:240
Zu @ react-lifecycles-compat.es.js:284
t.hydrate @ react-lifecycles-compat.es.js:290
(anonymous) @ index-csr.tsx:21
Promise.then (async)
j @ verify-stream.js:551
827 @ index-csr.tsx:20
r @ bootstrap:89
807 @ index.ts:16
r @ bootstrap:89
s @ bootstrap:45
n @ bootstrap:32
(anonymous) @ 85.4b71ce8d.chunk.js:2
7The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

Error:
<img width="308" alt="image" src="https://user-images.githubusercontent.com/720437/176053724-013ad7df-3109-4fb5-a674-1644cd58a670.png">

**Comment by matusfaro** [comment]
ClearFlask on AWS does work and I use it for hosting the cloud version of ClearFlask, but the setup can be done many different ways so there's going to be issues. Before continuing, I just want to point out the Docker deployment works out of the box for small installations OR you can also use the cloud version of ClearFlask which ends up being much cheaper then hosting all the resources in AWS yourself.

If you want to still continue, here are a few tips:

- It looks like you are running CF inside Docker on an EC2 instance. Not sure how you setup the networking there but the HTTP 463 seems to indicate some kind of networking loop.
- If you are going to use EC2, you can install CF on Amazon Linux and create an AMI using these [handy scripts](https://github.com/clearflask/clearflask/tree/master/clearflask-server/src/main/resources/deploy) including `cf-ami-create.sh` and `cf-instance-startup.sh`. This allows you to setup auto-scaling to put behind ALB.
- There isn't any more detailed logging on the frontend, it's a simple Express app for SSR

**Comment by neldridge** [comment]
Yeah, it's more difficult (generally) to get costs approved for a cloud service than to standup our own copy. We have considerations for security and finance to work through; I appreciate you being cost conscientious. Also, I think we want SSO as a baseline requirement and with expected users it will end up being cheaper for us long term.

```
It looks like you are running CF inside Docker on an EC2 instance. Not sure how you setup the networking there but the HTTP 463 seems to indicate some kind of networking loop.
```

Correct, I used the provided compose file to startup without the dependencies profile; the docker networking is default. 

I'm not really sure how best to check for a networking loop, where do you think this would be happening to cause this error?

In the mean time, I'll see if I can get an AL2 instance up to run the scripts against.

**Comment by neldridge** [comment]
Took me some time but I managed to get things running as I think they're expected using Tomcat and the Connect service. 

I'm still receiving a 463. At first I was getting a CONNREFUSED from the Connect service because it was resolving my ideas.sub.domain.com to the EC2 instance and not the ALB. The instance is not listening on 443, so by removing the hosts entry it was hitting my ALB. That's when I started receiving the 463. 

So, your initial guess is correct, it appears to be a network loop. I may have something misconfigured but I'm not sure what. Should the API Base bath be something local to the machine? That doesn't seem right, it should be pointing to my ALB, correct?

**Comment by neldridge** [comment]
I've fixed it, I misunderstood the purpose of the apiBasePath, which is to point to the tomcat instance not the public url.

Thanks.
